---
title: "Module Information"
number_sections: false
unnumbered: true
---

# Module information {-}

## Lecturer information {-}
This is a ten credit module, taught during semester one by Dr. Pete Philipson. My contact details are:  

Dr. Pete Philipson  
Herschel Building, Room 3.14  
peter.philipson1@ncl.ac.uk 
    
I have reserved Tuesdays 1pm - 2pm  and Thursdays 11am - 12pm (both from week 3 onwards) as "student support hours" for this module. Beyond this, I operate an open-door policy so you are welcome to drop by at your own convenience - there will be a timetable outside my door to help find a suitable time.

## Module schedule {-}
- Two lectures per week: Tuesdays 11am - 12pm (LT2) \& Wednesdays 10am - 11am (LT3) 

- Computer practical sessions in weeks 3, 5, 7, 9 \& 11 (Thursday 3pm - 4pm) of the semester in the Herschel Cluster

Note that the term has a reading/self-study week following week 6 so there are no timetabled sessions for a week at this juncture.

## Course materials {-}
All course materials will be available from Canvas. Announcements will also be made on Canvas and to your University email address. 

## Assessment {-}
The module will be assessed by two assignments - one summative assessment worth 20\% of the credit for the module, and one formative assessment (worth 0\% of the credit) - and a written exam in January 2026, which will be worth the remaining $80\%$ of the module credit.

The provisional in-course-assessment schedule can be found below. Submission will be electronic, via Canvas, at 4pm on the specified day.

```{r assessched, echo=FALSE, results='asis', tab.cap="Provisional in-course-assessment schedule."}
library(knitr)
library(kableExtra)
schedule <- data.frame(
    "Type" = c("Formative", "Summative"),
    "Weight (%)" = c(0, 20),
    "Release date" = c("Wednesday 1st October", "Wednesday 29th October"),
    "Submission date" = c("Wednesday 15th October", "Wednesday 12th November"),
  check.names = FALSE
)
kable(schedule) #%>%
  #kable_styling(latex_options = "hold_position") %>%
  #row_spec(0, bold = TRUE) %>% # optional: bold header
  #row_spec(1:nrow(schedule), extra_latex_after = "\\addlinespace")
```

## Relevant texts {-}
<div style="display:none;">

@Fox1997;
@Weisberg2005;
@Harrell2015;
@Sheather2009;
@Faraway2014.

</div>

::: {#refs}
:::

